version: '3.8'

services:
  mysqldbkube:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - static-files:/usr/static/images
  app:
    depends_on:
      - mysqldbkube
      - cache
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      DB_HOST: mysqldbkube
      DB_USER: $MYSQLDB_USER
      DB_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      DB_NAME: $MYSQLDB_DATABASE
      DB_PORT: $MYSQLDB_DOCKER_PORT
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    stdin_open: true
    tty: true
    links:
      - cache
    volumes:
      - ./:/src
  cache:
    image: "redis:alpine"
    restart: always
    expose:
      - "6379"
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

volumes: 
  db:
  static-files: {}
  cache:
    driver: local

