apiVersion: v1
kind: Service
metadata:
  name: mysqldbkube
spec:
  ports:
    - name: "3309"
      port: 3309
      targetPort: 3306
  selector:
    app: mysqldbkube
  clusterIP: None
status:
  loadBalancer: {}
