apiVersion: v1
kind: Service
metadata:
  labels:
    app: cache
  name: cache
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
    - name: "0"
      port: 0
      targetPort: 0
  selector:
    app: cache
status:
  loadBalancer: {}
