pipeline {

  environment {
    dockerimagename = "andremaria1980/jenkins"
    dockerImage = ""
  }

  agent any

  stages {

    stage("Fix the permission issue") {

        agent any

        steps {
            sh "sudo chown root:jenkins /run/docker.sock"
        }

    }

    stage('Checkout Source') {
      steps {
        git url:'https://github.com/AndreMariaDev/kubenetes-nestjs-mysql.git', branch: 'main', credentialsId: '73a6300e-fe00-4272-8e6f-b6d3ac373eb0'
      }
    }

    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build dockerimagename
        }
      }
    }

    stage('Pushing Image') {
      environment {
               registryCredential = 'dockerhublogin'
           }
      steps{
        script {
          docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
            dockerImage.push("v1")
          }
        }
      }
    }

    stage('Deploying App to Kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "kube/app-deployment.yaml", kubeconfigId: "kubernetes")
        }
      }
    }

  }

}