pipeline {

  environment {
    dockerimagename = "andremaria1980/v1"
    dockerImage = ""
  }

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git 
          url 'https://github.com/AndreMariaDev/kubenetes-nestjs-mysql.git',
          branch: 'main', 
          credentialsId: '859cc0da-2843-43c4-80c3-f291114ab039'
      }
    }

    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build dockerimagename
        }
      }
    }

    stage('Pushing Image') {
      environment {
               registryCredential = 'dockerhublogin'
           }
      steps{
        script {
          docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
            dockerImage.push("v1")
          }
        }
      }
    }

    stage('Deploying App to Kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "kube/app-deployment.yaml", kubeconfigId: "kubernetes")
        }
      }
    }

  }

}